simpledatastackdbt:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: kaisahlingtutorial
      dataset: data_warehouse
      location: europe-west3
      threads: 1
      retries: 1
      timeout_seconds: 300
